//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditerka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baskets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Baskets()
        {
            this.BasketsCatalogs = new HashSet<BasketsCatalogs>();
        }
    
        public int IdBasket { get; set; }
        public int IdUser { get; set; }
        public decimal TotalPrice { get; set; }
        public bool IsOrdered { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasketsCatalogs> BasketsCatalogs { get; set; }
    }
}
