//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konditerka
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersCatalogs
    {
        public int IdOrderCatalog { get; set; }
        public int IdOrder { get; set; }
        public int IdCatalog { get; set; }
        public int Quantity { get; set; }
    
        public virtual Catalogs Catalogs { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
